{% set name = "consel" %}
{% set version = "0.20" %}

package:
  name: consel
  version: {{ version }}

source:
  url: http://stat.sys.i.kyoto-u.ac.jp/prog/consel/pub/cnsls020.tgz
  sha256: cc6e8ee6077693817db475229aa47b9d9fb66bf5f48a3aace63e4b525f05238b

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('consel', max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}

test:
  commands:
    - catass -h 2>&1 | grep 'error in command line.'
    - catci -h 2>&1 | grep 'error in command line.'
    - catmt -h 2>&1 | grep 'error in command line.'
    - catpv -h 2>&1 | grep 'must specify input-file.'
    - catrep -h 2>&1 | grep 'error in command line.'
    - consel -h 2>&1 | grep 'error in command line.'
    - makerep -h 2>&1 | grep 'error in command line.'
    - makermt -h 2>&1 | grep 'error in command line.'
    - randrep -h 2>&1 | grep 'error in command line.'
    - seqmt -h 2>&1 | grep 'error in command line.'
    - treeass -h 2>&1 | grep 'error in command line.'

about:
  home: "https://stat.sys.i.kyoto-u.ac.jp/prog/consel"
  license: "GPL-2.0-or-later"
  license_family: GPL
  summary: "CONSEL calculates the probability value (i.e., p-value) to assess the confidence in the selection problem."
  doc_url: "https://stat.sys.i.kyoto-u.ac.jp/prog/consel"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
