{% set name = "concoct" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/BinPro/CONCOCT/archive/{{ version }}.tar.gz
  sha256: 00aecacb4b720ac123a63e65072c61e0b5a8690d844c869aaee4dbf287c82888
  patches:
    - concoct-newer-scikit-learn.patch

build:
  preserve_egg_dir: True
  number: 7
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python 3.12.*
    - setuptools 68.2.2.*
    - cython 0.29.36.*
    - numpy 1.26.4
    - gsl 2.7.*
  run:
    - python 3.12.*
    - setuptools 68.2.2.*
    - cython 0.29.36.*
    - {{ pin_compatible('numpy') }}
    - scipy 1.14.1.*
    - pandas 2.2.2.*
    - biopython 1.81.*
    - pytz 2023.3.*
    - scikit-learn 1.5.2.*
    - nose 1.3.7.*
    - gsl 2.7.*
    - samtools 1.21.*

test:
  commands:
    - concoct -h
  imports:
    - concoct

about:
  home: https://github.com/BinPro/CONCOCT
  license: FreeBSD
  summary: 'Clustering cONtigs with COverage and ComposiTion'
  license_family: BSD

extra:
  additional-platforms:
    - linux-aarch64
  skip-lints:
    - uses_setuptools  # concoct uses pkg_resources
    - cython_must_be_in_host # Cython needs to be in run as well currently
  identifiers:
    - doi:10.1038/nmeth.3103
