{% set name = "emvc-2" %}
{% set version = "1.0" %} # Remember to update sha256 below

package:
  name: emvc-2
  version: '{{ version }}'

source:
  url: https://github.com/guilledufort/EMVC-2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 'edee7e027bb720f625cfc3073798ab39916f1852641cc7f05604ff62b905c7e3'

build:
  number: 4
  # platforms:
  #   - osx-64
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  run:
    - python
    - samtools
    - numpy
    - scipy
    - tqdm
    - scikit-learn
    
test:
  commands:
    - "emvc-2 -h"

about:
  home: https://github.com/guilledufort/EMVC-2
  license: MIT
  license_family: MIT
  summary: An efficient SNV variant caller based on the expectation maximization algorithm.

extra: 
  additional-platforms:
    - linux-aarch64
