{% set name = "fusioncatcher" %}
{% set version = "1.33" %}
{% set sha256 = "7a1b3b0cf699b030d1bebe83b898ed594988be96b87c3ac31f3d768b31de534a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ndaniel/fusioncatcher/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - paths.patch

build:
  number: 6
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  run:
    - python <3
    - biopython >=1.50
    - bowtie =1.2.3
    - fusioncatcher-seqtk =1.2
    - star
    - bowtie2 =2.3.5
    - bbmap
    - ucsc-blat
    - ucsc-faToTwoBit
    - ucsc-liftover
    - lzo
    - bwa =0.7.19
    - velvet =1.2.10
    - openpyxl =2.5.0a2
    - xlrd =1.0.0
    - pigz =2.8
    - samtools =0.1.19
    - picard =2.10.6
    - numpy =1.13.1
    - parallel =20171222
    - oases
    - lzop
    - openjdk
    - sra-tools
    - zip
    - coreutils
    - grep
    - fastqtk
    - tbb-devel <2021.1.1
    - gzip
    - wget

test:
  commands:
    - export FC_DB_PATH=${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}/db && fusioncatcher.py -h
    - export FC_DB_PATH=${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}/db && fusioncatcher-build.py -h

about:
  home: "https://github.com/ndaniel/fusioncatcher"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Finder of Somatic Fusion Genes in RNA-seq data."
  dev_url: "https://github.com/ndaniel/fusioncatcher"

extra:
  identifiers:
    - doi:10.1101/011650
  notes: download-human-db.sh should be updated when new version of FusionCatcher is released.
