{% set name = "pbstarphase" %}
{% set version = "1.4.2" %}
{% set sha256 = "b4c038515ccca1ff05f8f564e2a034338e118560a2e922c5d5d3c8e490168d0a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/PacificBiosciences/pb-StarPhase/archive/v{{ version }}.tar.gz
    sha256: eed919e749b2a1ec48603129b541f21d529b52185a4ffd496230cd2f5a592805
    folder: source

build:
  number: 1
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - zlib

test:
  commands:
    - test -f ${PREFIX}/bin/pbstarphase
    - pbstarphase 2>&1 | grep "Usage"
    - pbstarphase --help

about:
  home: "https://github.com/PacificBiosciences/pb-StarPhase"
  license: "BSD-3-Clause-Clear"
  summary: "A phase-aware pharmacogenomic diplotyper for PacBio sequencing data."
  dev_url: "https://github.com/PacificBiosciences/pb-StarPhase"

extra:
  recipe-maintainers:
    - holtjma
    - ctsa
    - zeeev
  skip-lints:
    - should_use_compilers
    - should_be_noarch_generic
  additional-platforms:
    - linux-aarch64