{% set name = "cvlr" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/EmanueleRaineri/cvlr/archive/292190acc1bc1d954810d00be9a0c1fabd6a3646.zip
  sha256: eaceaa530925cc42aafdda32d9d6dfb73c26cb6eccc06615947545a6126fb46a 

build:
  number: 6
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - htslib
    - libdeflate
    - zlib
    - curl
    - xz
    - openssl
    - bzip2
  run:
    - python >=3
    - numpy
    - matplotlib-base

test:
  commands:
    - which cvlr-cluster
   #- cvlr-meth-of-bam --help
    - cvlr-stats.py -h

about:
  home: https://github.com/EmanueleRaineri/releases/
  license: MIT
  license_family: MIT
  summary: Clustering and Visualization of Long Reads

extra:
  additional-platforms:
    - linux-aarch64
