{% set name = "perl-string-approx" %}
{% set version = "3.28" %}
{% set sha256 = "43201e762d8699cb0ac2c0764a5454bdc2306c0771014d6c8fba821480631342" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/J/JH/JHI/String-Approx-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl >=5.26
    - perl-test-more
    - perl-extutils-makemaker
  run:
    - perl >=5.26
    - perl-test-more

test:
  imports:
    - String::Approx

about:
  home: "https://metacpan.org/pod/String::Approx"
  license: Unknown
  summary: "Perl extension for approximate matching (fuzzy matching)."
  doc_url: "https://metacpan.org/pod/String::Approx"

extra: 
  additional-platforms:
    - linux-aarch64
    - osx-arm64
