{% set version = "0.5.1" %}

package:
  name: hesslab-gambit
  version: "{{ version }}"

source:
  url: https://github.com/jlumpe/gambit/archive/v{{ version }}.tar.gz
  sha256: a174512809e3fcc074384253e6493129ffee76d7439a1e5698cb9686111a76b6

build:
  number: 1
  script: |
    export NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
    {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv
    {{ PYTHON }} -c "
    import os
    from pkg_resources import resource_filename
    mig_dir = resource_filename('gambit', 'db/migrations')
    assert os.path.exists(os.path.join(mig_dir, 'alembic.ini')), 'Migration files missing!'
    "
    #"{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  skip: True  # [py < 37]
  run_exports:
    - {{ pin_subpackage('hesslab-gambit',max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python >=3.7,<3.9
    - pip
    - numpy >=1.16,<1.20
    - cython >=0.29.21,<0.30
  run:
    - python >=3.7,<3.9
    - numpy >=1.16,<1.20
    - sqlalchemy >=1.3,<2.0
    - biopython >=1.69
    - alembic >=1.0,<2.0
    - attrs >=20
    - cattrs >=1.0
    - click >=7.0
    - h5py >=3.0
    - setuptools

test:
  requires:
    - pytest
  source_files:
    - tests/
  imports:
    - gambit
  commands:
    # Just check command is available
    - gambit --help
    - pytest tests/ -v -k "not test_db_migrate"

about:
  home: https://github.com/jlumpe/gambit
  summary: 'IMPORTANT: This recipe is out of date. Use "gambit" instead: http://bioconda.github.io/recipes/gambit/README.html'
  description: |
    GAMBIT (Genomic Approximation Method for Bacterial Identification and Tracking)
    is a tool for rapid taxonomic identification of microbial pathogens. It uses an
    extremely efficient genomic distance metric along with a curated database of
    approximately 50,000 reference genomes (derived from NCBI RefSeq) to identify
    unknown bacterial genomes within seconds.
  license: AGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://gambit-genomics.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - jlumpe
  additional-platforms:
    - linux-aarch64
