{% set name = "blat" %}
{% set version = "36" %}
{% set sha256 = "4b0fff006c86dceb7428922bfb4f8625d78fd362d205df68e4ebba04742d2c71" %}

package:
  name: blat
  version: {{ version }}

source:
  url: http://hgwdev.cse.ucsc.edu/~kent/src/blatSrc{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 1
  run_exports: 
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - libpng
    - zlib
    - mysql-libs
  run:
    - libpng
    - zlib
    - mysql-libs
    
test:
  commands:
    - 'blat | grep -q "^blat - Standalone BLAT"'

about:
  home: https://genome.ucsc.edu/FAQ/FAQblat.html
  license: Free for academic, nonprofit and personal use
  summary: BLAT is a bioinformatics software tool which performs rapid mRNA/DNA and cross-species protein alignments.

extra:
  identifiers:
    - biotools:blat
  additional-platforms:
    - linux-aarch64
