{% set name = "deltapd" %}
{% set version = "0.1.5" %}
{% set sha256 = "e55f57e5792baa37af5e5ae3d0b37b5cf847f0a04800655491a80bb4a8252378" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deltapd-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - pdm.patch

build:
  number: 7
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps --no-cache-dir --use-pep517 -vvv
  entry_points:
    - deltapd = deltapd.__main__:main
  run_exports:
    - {{ pin_subpackage('deltapd', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - python >=3.10,<3.11
    - {{ pin_compatible('numpy') }}
    - setuptools
    - pip
  host:
    - pip
    - python >=3.10,<3.11
    - cython
    - numpy >=1.21,<1.22
  run:
    - python >=3.10,<3.11
    - {{ pin_compatible('numpy') }}
    - phylodm
    - tqdm
    - ete3
    - dendropy
    - matplotlib-base
    - jinja2
    - seaborn-base
    - numpy >=1.21,<1.22

test:
  imports:
    - deltapd
    - deltapd.file
  commands:
    - deltapd --version
    - deltapd --version > /dev/null 2>&1

about:
  home: https://github.com/Ecogenomics/DeltaPD
  license: "AGPL-3.0-only"
  license_family: AGPL
  license_file: LICENSE
  summary: 'DeltaPD is a tool used to determine outliers in a gene tree when compared against a reference tree.'
  dev_url: https://github.com/Ecogenomics/DeltaPD

extra:
  identifiers:
    - doi:10.5281/zenodo.4107213
  additional-platforms:
    - linux-aarch64
    - osx-arm64
