{% set version = '1.0' %}
{% set name = 'zerone' %}

package:
  name: zerone
  version: {{ version }}

source:
  url: https://github.com/nanakiksc/zerone/archive/5af03a1d0e6b4d8df20e04342c1facfe069ebb56.tar.gz
  sha256: 2d06066135c988f6b528a87b0fbad87cb93e82afce6a67d24e6efd828165a130

build:
  number: 8
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - zerone

about:
  home: https://github.com/nanakiksc/zerone
  dev_url: https://github.com/nanakiksc/zerone
  license: GPL-3
  summary: Zerone discretizes several ChIP-seq replicates simultaneously and resolves conflicts between them.
  license_family: GPL

extra: 
  additional-platforms:
    - linux-aarch64
