{% set name = "daisysuite" %}
{% set version = "1.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/eseiler/DaisySuite/repository/1.3.0/archive.tar.gz
  sha256: 57789b62a41dac5f7ab3fe9fe16bdf3ded47bb8adee6f19ffe7a45425bb1373a

build:
  noarch: generic
  number: 3
  run_exports: 
    - {{ pin_subpackage(name|lower) }}

requirements:
  run:
    - snakemake
    - sak
    - mason
    - gustaf
    - yara
    - bwa
    - clever-toolkit
    - stellar
    - samtools
    - bedtools
    - pandas
    - pysam
    - scipy
    - biopython

test:
  commands:
    - DaisySuite --no-hooks --configfile $PREFIX/opt/daisysuite/example/example.yaml --config outputdir="$PREFIX/opt/daisysuite/example/output" -n

about:
  home: https://gitlab.com/eseiler/DaisySuite
  license: "GNU GPLv3"
  summary: "DaisySuite - mapping-based pipeline for horizontal gene transfer (HGT) detection using sequencing data"

