# This file created by conda-build 2.0.7
# meta.yaml template originally from:
# /opt/recipe, last modified Thu May  4 13:51:18 2017
# ------------------------------------------------

package:
    name: validictory
    version: 1.0.1
source:
    fn: validictory-1.0.1.tar.gz
    md5: 59b619e446e7f8b510c2b76f0973b2e8
    url: https://pypi.python.org/packages/source/v/validictory/validictory-1.0.1.tar.gz
build:
    number: 1
    run_exports:
      - {{ pin_subpackage("validictory", max_pin="x.x") }}

requirements:
    build:
        - python <3.10
        - setuptools
    run:
        - python <3.10
test:
    imports:
        - validictory
        - validictory.tests
extra:
  additional-platforms:
    - linux-aarch64

about:
    home: http://github.com/jamesturk/validictory
    license: BSD License
    summary: general purpose python data validator
