{% set name = "demuxlet" %}
{% set version = "1.0" %}
{% set sha256  = "6ca1427b08461eac292623041d4808c7216e18e5ac0eade0c8245930853b68ff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 7
  skip: True # [osx]
  run_exports: 
    - {{ pin_subpackage(name|lower) }}

source:
  url: https://github.com/statgen/demuxlet/archive/b99026f9298f46d897a23f6e7909e462e1b1fa1b.zip
  sha256: {{ sha256 }}
  patches:
    - Makefile.am.patch

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - libtool
    - autoconf
    - automake
    - zlib
  host:
    - htslib >=1.10
    - zlib
  run:
    - samtools
    - htslib >=1.10
    - zlib

test:
  commands:
    - demuxlet -help 2>&1 | grep 'Detailed' 

about:
  home: https://github.com/statgen/demuxlet
  license: GPL3
  license_file: LICENSE
  summary: Genetic multiplexing of barcoded single cell RNA-seq
  dev_url: https://github.com/statgen/demuxlet
  doc_url: https://github.com/statgen/demuxlet

extra: 
  additional-platforms:
    - linux-aarch64
