package:
  name: r-rblast
  version: "1.3.1"

source:
  url:
    - https://github.com/mhahsler/rBLAST/archive/e1044a564cdf635debbeffd1e57557a9682b69f5.tar.gz
  md5: 942a913439807694358d4974a2e1b0b9

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  run_exports:
    - {{ pin_subpackage('r-rblast', max_pin="x.x") }}

requirements:
  host:
    - r-base >=3.6.3
    - bioconductor-biostrings
    - bioconductor-biocfilecache
  run:
    - r-base >=3.6.3
    - bioconductor-biostrings
    - blast

test:
  commands:
    - $R -e "library('rBLAST')" # [not win]
    - "\"%R%\" -e \"library('rBLAST')\"" # [win]

about:
  home: https://github.com/mhahsler/rBLAST
  license: GPL3
  summary: 'Seamlessly interfaces the Basic Local Alignment Search Tool (BLAST) to search genetic sequence data bases. This work was partially supported by grant no. R21HG005912 from the National Human Genome Research Institute.'

extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
