package:
  name: tssar
  version: "1.0.1"

source:
  url: http://nibiru.tbi.univie.ac.at/TSSAR/download/TSSAR_1.0.1.zip
  md5: 22f3c1fe591a566b0c31877fff6c31b9

build:
  number: 10
  skip: True  # [osx]
  run_exports:
    - {{ pin_compatible('tssar', exact=True) }}

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - conda-forge::r-base 
  run:
    - conda-forge::r-base 
    - r-vgam
    - r-skellam
    - perl

test:
  commands:
    - TSSAR --help | grep "help"

about:
  home: http://rna.tbi.univie.ac.at/TSSAR
  license: GNU General Public License v2.0
  summary: TSSAR is a Web Service for predicting bacterial Transcription Start Sites from dRNA-seq data.

extra: 
  additional-platforms:
    - linux-aarch64
