{% set name = "Sample_grouping" %}
{% set version = "1.0.0" %}
{% set sha256 = "2ef84fe0aeee31b18bf1147b8785cd55579a896d4435fb5d12a078a510122d2a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SantaMcCloud/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  run_exports:
    - {{ pin_subpackage("sample_grouping", max_pin="x") }}

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - pandas

test:
  commands:
    - reorder_reads.py --help
    - reorder_reads.py --version

about:
  home: https://github.com/SantaMcCloud/Sample_grouping
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: "A tool for merging reads based on metadata groups."
  dev_url: https://github.com/SantaMcCloud/Sample_grouping
