{% set name = "domclust" %}
{% set version = "1.2.8" %}
package:
  name: {{ name }}
  version: {{version }}

about:
  home: http://mbgd.genome.ad.jp/domclust/
  license: GPL3
  summary: Effective tool for orthologous grouping in multiple genomes

build:
  number: 0
  run_exports: 
    - {{ pin_subpackage(name|lower) }}
source:
  url: "https://depot.galaxyproject.org/software/DomClust/DomClust_1.2.8_src_all.tar.gz"
  sha256: ffe3dac8dee1ccd621556ed7e5818299ed167853dd4dcd9e42cde43eec4c40b2

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - perl
    - libcxx # [osx]
  run:
    - libcxx # [osx]
    - perl

test:
  commands:
    - domclust -h

extra: 
  additional-platforms:
    - linux-aarch64
