{% set version = "1.2" %}
package:
  name: harvesttools
  version: '{{version}}'

source:
    - url: https://github.com/marbl/harvest-tools/archive/refs/tags/v{{ version }}.tar.gz # [linux]
      sha256: 6f9a7ab056d52fad78bdb7a93832ff8b509b77566c22481a2d81089736e10af4 # [linux]
    - url: '{{base}}/v{{version}}/harvesttools-OSX64-v{{version}}.zip'     # [osx]
      sha256: '{{sha256osx}}' # [osx]


build:
  number: 3
  run_exports:
    - {{ pin_subpackage('harvesttools',max_pin="x") }}

requirements:
  host:
    - zlib
    - protobuf
    - capnproto
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake
    - protobuf
    - libprotobuf
    - libprotobuf-static
    - zlib
    - autoconf
    - capnproto
    - pkg-config
    - abseil-cpp >=20210324
  run:
    - libgcc
    - libstdcxx

test:
  commands:
    - harvesttools -h >/dev/null

about:
  home: https://github.com/marbl/harvest-tools
  license: "custom; see https://raw.githubusercontent.com/marbl/harvest-tools/master/LICENSE.txt"
  summary: HarvestTools is a part of the Harvest software suite and provides file conversion between Gingr files and various standard text formats

extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
  additional-platforms:
    - linux-aarch64
