{% set version = "1.0.3" %}

package:
  name: transrate
  version: {{ version }}

source:
  url: https://github.com/blahah/transrate/archive/v{{ version }}.tar.gz
  sha256: 2ccb101cfab5a33586ea9e62af2b2f14caf6bc016724d1fef796b427e39fe100
  patches:
    - patch

build:
  number: 7
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage("transrate",max_pin="x.x") }}	

requirements:
  build:
    - {{ compiler('c') }} =12
    - make
    - libxcrypt
  host:
    - ruby
    - rb-bundler
    - zlib =1.3.1
  run:
    - ruby
    - rb-bundler
    - boost 
    - snap-aligner 
    - salmon
    - zlib =1.3.1
    - transrate-tools 1.0.0 

test:
  commands:
    - transrate --help
    - snap-aligner 2>&1 | grep "SNAP version" > /dev/null
    - salmon quant -h

about:
  home: https://github.com/blahah/transrate/
  license: MIT
  license_file: LICENSE
  summary: Reference free quality assessment of de-novo transcriptome assemblies

extra:
  identifiers:
    - doi:10.1101/gr.196469.115
  additional-platforms:
    - linux-aarch64
