{% set version = "0.0.1" %}

package:
  name: ls-gkm
  version: {{ version }}

source:
  url: https://github.com/Dongwon-Lee/lsgkm/archive/164a4a48f6387e67b5d955db932f8a403de6c321.zip
  sha256: 029faf96bdc98e441132801d6e1cce032ec2f718972e214aaca40ad756c83f3e

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('ls-gkm', max_pin='x.x') }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}

  run:

test:
  commands:
    - gkmtrain
    - gkmpredict

about:
  home: https://github.com/Dongwon-Lee/lsgkm
  license: GPL3
  license_file: LICENSE
  summary: gkm-SVM, a sequence-based method for predicting regulatory DNA elements.
