{% set version = "0.3.1" %}
{% set name = "ontime" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mbhall88/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1caee3197d1032da38c55a47c3b626fe00b07831362e734fb2174747fca17fc4

build:
  number: 2 
  run_exports:
    - {{ pin_subpackage('ontime', max_pin="x.x") }}

requirements:
  build:
    - rust >=1.65,<1.80  # 限制Rust版本避免API冲突^:ml-citation{ref="3" data="citationList"}
    - {{ compiler('c') }}
  host:
    - time >=0.3.35  # 显式声明兼容版本^:ml-citation{ref="3" data="citationList"}


test:
  commands:
    - ontime --help

about:
  home: https://github.com/mbhall88/ontime
  license: MIT
  license_family: MIT
  summary: Extract subsets of ONT (Nanopore) reads based on time
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbhall88
  additional-platforms:
    - linux-aarch64      
