{% set version = "5.0.1" %}

package:
  name: methpipe
  version: {{ version }}

source:
  url: https://github.com/smithlabcode/methpipe/releases/download/v{{ version }}/methpipe-{{ version }}.tar.gz
  md5: 735bdafc5b25ae6df30e43442127571e

build:
  number: 6
  run_exports:
    - {{ pin_subpackage('methpipe', max_pin='x.x') }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gsl
    - zlib
    - htslib
  run:
    - gsl
    - zlib
    - htslib

about:
  home: https://github.com/smithlabcode/methpipe
  license: GPL-3
  license_file: LICENSE
  license_family: GPL-3
  summary: A pipeline for analyzing DNA methylation data from bisulfite sequencing.
test:
  commands:
    - methcounts

extra:
  additional-platforms:
    - linux-aarch64
