{% set version = '8.0.112' %}

package:
  name: java-jdk
  version: {{ version }}

build:
  number: 2

requirements:
  run:
    - openjdk >=8.0.282

test:
  commands:
    - java -version

about:
  home: http://www.azulsystems.com/products/zulu
  license: GPL
  summary: The Zulu OpenJDK build.

extra:
  additional-platforms:
    - linux-aarch64
