{% set version = '8.0.112' %}

package:
  name: java-jdk
  version: {{ version }}

build:
  number: 2
  noarch: generic
  run_exports:
    - {{ pin_subpackage('java-jdk', max_pin='x.x') }}

requirements:
  run:
    - openjdk >=8.0.282

test:
  commands:
    - java -version

about:
  home: http://www.azulsystems.com/products/zulu
  license: GPL-3.0
  #  license_file: LICENSE
  summary: The Zulu OpenJDK build.

