{% set name = "gotohscan" %}
{% set version = "1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://www.bioinf.uni-leipzig.de/Software/GotohScan/GotohScan-{{ version }}.tar.gz
  sha256: 5a14fcd7b29b59af885bce2a71c648cc8b4eb18ad70b5aa93e5bc63d638ae49d

build:
  number: 8
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}

test:
  commands:
    - GotohScan -h

about:
  home: "https://www.bioinf.uni-leipzig.de"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A search tool that finds shorter sequences (usually genes) in large database sequences (chromosomes, genomes, ..) by computing all semi-global alignments."
  doc_url: "https://www.bioinf.uni-leipzig.de"

extra: 
  additional-platforms:
    - linux-aarch64
