{% set name = "tclap" %}
{% set version = "1.2.3" %}
package:
    name: {{ name }}
    version: {{ version }}
source:
    sha256: 4fc052614f3377e2ff9077637720a62c30adf817c649c03cc6f93dacdbeee7f1
    url: https://github.com/mirror/tclap/archive/v1.2.3.tar.gz
build:
    number: 0
    run_exports:
    - {{ pin_subpackage(name,max_pin="x.x") }}
requirements:
    build:
        - gcc 
        - gxx
        - autoconf 2.69
        - automake 1.16.2 
        - ca-certificates 2020.12.5 
        - libffi 3.3 
        - libgcc-ng 9.3.0 
        - libgomp 9.3.0 
        - libstdcxx-ng 9.3.0 
        - m4 1.4.18 
        - make 4.3 
        - ncurses 6.2 
        - openssl 1.1.1i
        - perl 5.32.0 
        - pkg-config 0.29.2 
        - pkgconfig 1.4.0 
        - python 3.9.1 
        - python_abi 3.9 
        - readline 8.0 
        - sqlite 3.34.0 
        - tk 8.6.10 
        - tzdata 2020f he74cb21_0
        - xz 5.2.5 
        - zlib 1.2.11 
    host:
        - libgcc-ng 9.3.0 
        - libgomp 9.3.0
        - libstdcxx-ng 9.3.0 
    run:
        - libgcc-ng >=9.3.0
        - libstdcxx-ng >=9.3.0
test:
    commands:
        - test -d ${PREFIX}/include/tclap
about:
    dev_url: https://sourceforge.net/projects/tclap/
    doc_url: http://tclap.sourceforge.net/manual.html
    home: http://tclap.sourceforge.net
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: TCLAP is a small, flexible library that provides a simple interface for
        defining and accessing command line arguments.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - marcelotrevisani
    additional-platforms:
        - linux-aarch64

