{% set name = "plmc" %}
{% set version = "20221105" %}
{% set sha256 = "3141129e9c9e9185ffb5abd728e8f9de789e8056e96a92ba6cce38b5d16b67e4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 2
  skip: True  # [aarch64 and py2k]  # 跳过 ARM64 上的 Python 2 构建
  run_exports:
    - {{ pin_subpackage('plmc', max_pin='x.x') }}  

source:
  url: https://github.com/debbiemarkslab/{{ name|lower }}/archive/refs/heads/master.zip
  sha256: {{ sha256 }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - clangdev
    - llvm-openmp
  host:
    - llvm-openmp
  run:
    - llvm-openmp

test:
  commands:
    - which {{ name }}

about:
  home: https://github.com/debbiemarkslab/plmc
  license: MIT
  license_file: LICENSE
  summary: 'Inference of couplings in proteins and RNAs from sequence variation.'

extra:
  additional-platforms:
    - linux-aarch64
