{% set version = "1.3.0" %}

package:
  name: metawrap-mg
  version: {{ version }}

source:
  # self-reports as 1.3.0, but tag is v1.3
  url: https://github.com/bxlab/metaWRAP/archive/v1.3.tar.gz
  sha256: ffdbccf340dc0b1ebd0ad6f222e3bdef1e22bbd6e4e5156bf93500a3a834dd52

build:
  noarch: generic
  number: 2
  run_exports:
    - {{ pin_subpackage('metawrap-mg',max_pin="x.x") }}

requirements:
  run:
    - python >=2.7,<3.0
    - perl >=5.26,<5.27
    - perl-xml-simple
    - perl-bioperl
    - openssl >=1.0,<2.0
    - biopython >=1.68,<1.70
    - bowtie2 >=2.3.5,<3.0
    - bwa >=0.7.17,<1.0
    - checkm-genome >=1.0.12
    - fastqc >=0.11.8,<0.12
    - krona >=2.7,<3.0
    - matplotlib-base >=2.2.3,<3.0
    - pandas >=0.24.2,<1.0
    - r-base >=3.5.1,<4.0
    - r-ggplot2 >=3.1.0,<4.0
    - r-reshape2
    - seaborn >=0.9.0,<0.10
    - kraken >=1.1  # [x86_64]
    - kraken2 >=2.0,<3.0
    - salmon >=0.13.1  # [x86_64]
    - taxator-tk >=1.3.3e  # [x86_64]
    - minimap2 >=2.17  # [aarch64]
    - bwa-mem2 >=2.0  # [aarch64]
    - blast >=2.6.0,<3.0  # [not arm64]
    - bmtagger >=3.101  # [not arm64]
    - concoct >=1.0.0,<2.0  # [not arm64]
    - maxbin2 >=2.2.6,<3.0  # [not arm64]
    - megahit >=1.1.3,<1.2  # [not arm64]
    - metabat2 >=2.12.1,<3.0  # [not arm64]
    - pplacer >=1.1.alpha19  # [not arm64]
    - prokka >=1.13,<1.14  # [not arm64]
    - quast >=5.0.2,<6.0  # [not arm64]
    - spades >=3.13.0,<4.0  # [not arm64]
    - trim-galore >=0.5.0,<0.6  # [not arm64]

test:
  commands:
    - "metawrap --version | grep 'metaWRAP v={{ version }}'"
    - "metawrap read_qc | grep 'Usage: metaWRAP read_qc'"
    - which config-metawrap
  requires:
    - perl  # [not arm64]

about:
  home: https://github.com/bxlab/metaWRAP
  license: MIT
  summary: "MetaWRAP is a pipeline for genome-resolved metagenomic data analysis"

extra: 
  additional-platforms:
    - linux-aarch64
