{% set version = "1.3.0" %}

package:
  name: metawrap-mg
  version: {{ version }}

source:
  # self-reports as 1.3.0, but tag is v1.3
  url: https://github.com/bxlab/metaWRAP/archive/v1.3.tar.gz
  sha256: ffdbccf340dc0b1ebd0ad6f222e3bdef1e22bbd6e4e5156bf93500a3a834dd52

build:
  noarch: generic
  number: 2
  run_exports:
    - {{ pin_subpackage('metawrap-mg', max_pin="x.x") }}

requirements:
  run:
    - python >=3.8
    - biopython
    - blas
    - blast >=2.7.1
    - bmtagger =3.101
    - bowtie2 =2.3.5
    - bwa =0.7.17
    - checkm-genome =1.0.12
    - concoct =1.0.0
    - fastqc =0.11.8
    - kraken =1.1.1.*
    - krona =2.7
    - matplotlib-base >=3.0
    - maxbin2 =2.2.6
    - megahit =1.1.3
    - metabat2 =2.12.1
    - pandas >=1.0
    - perl-bioperl-core 
    - pplacer
    - prokka >=1.14.6
    - quast
    - r-ggplot2 =3.1.0
    - r-reshape2
    - r-recommended =3.5.1
    - salmon >=1.0
    - samtools >=1.10
    - seaborn >=0.11
    - spades =3.13.0
    - taxator-tk >=1.4
    - trim-galore =0.5.0
    - boost-cpp >=1.72
    - zlib >=1.2.11
    # not direct dependencies, only here to speed up dependency resolution

test:
  commands:
    - "metawrap --version | grep 'metaWRAP v={{ version }}'"
    - "metawrap read_qc | grep 'Usage: metaWRAP read_qc'"
    - which config-metawrap

about:
  home: https://github.com/bxlab/metaWRAP
  license: MIT
  summary: "MetaWRAP is a pipeline for genome-resolved metagenomic data analysis"
