{% set name = "gctb" %}
{% set version = "2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://cnsgenomics.com/software/{{ name }}/download/{{ name }}_{{ version }}_Linux.zip #[linux and x86_64]
  sha256: 800729daafccd5f21f39a1b9f19f1da08b36fef630a921ec22a223becea99b7b                     #[linux and x86_64]
  url: https://cnsgenomics.com/software/gctb/download/gctb_2.0_scr.zip                         #[linux and aarch64]
  sha256: 47c50f1f1220401fca34c5467fd118ff41ebfc9887e04400ceeb13abaf22d0bd                     #[linux and aarch64]
build:
  skip: true  # [osx]
  number: 4
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - eigen
    - boost
  run:
    - eigen
    - boost
  host:
    - eigen
    - boost

test:
  commands:
    - gctb

about:
  home: "https://cnsgenomics.com/software/gctb"
  license: MIT
  summary: GCTB (Genome-wide Complex Trait Bayesian ) is a software tool that comprises a family of Bayesian linear mixed models for complex trait analyses using genome-wide SNPs.

extra: 
  additional-platforms:
    - linux-aarch64
