{% set version = "2.1.1" %}
{% set sha256 = "ef0e9c646d246f1670fc1fbeff2d89dfa7d32b6de42b2daad79807c69f2866fb" %}

package:
  name: mdasim
  version: {{ version }}

source:
  url: https://github.com/hzi-bifo/mdasim/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # omitting OSX as the Makefile wasn't made for this (tried debugging, never ends)
  number: 7
  run_exports:
    - {{ pin_subpackage('mdasim', max_pin='x.x') }}
  noarch: generic
  script: sed -i 's/-m64/-mcpu=cortex-a53/g' Makefile && make prefix=$PREFIX CPP="${CXX} ${CXXFLAGS} ${CPPFLAGS} ${LDFLAGS}"

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - openmpi
  run:
    - openmpi

test:
  commands:
    - mdasim --help
    - mdasim --version

about:
  home: https://github.com/hzi-bifo/mdasim
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'This is MDAsim 2+, a tool to simulate whole genome amplification'

extra:
  additional-platforms:
    - linux-aarch64  
