package:
  name: "visceral-evaluatesegmentation"
  version: "2021.03.25"

source:
  url: https://github.com/Visceral-Project/EvaluateSegmentation/archive/master.zip
  sha256: 88ef07e0221dee16921658de4250a45bde4a1c096b98682f3ffc397b5fcfcc29

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage('visceral-evaluatesegmentation', max_pin=None) }}

requirements:
  build:
    - libitk-devel
    - libitk 5.3.0
    - make
    - {{ compiler('cxx') }}
    - cmake
  host:
    - libitk-devel
    - libitk 5.3.0
  run:
    - libitk-devel
    - libitk 5.3.0
    - jpeg

test:
  commands:
    - EvaluateSegmentation --help

about:
  home: "https://github.com/Visceral-Project/EvaluateSegmentation"
  license: "Apache-2.0"
  summary: "EvaluateSegmentation is a tool that compares two volumes (a test segmentation and a ground truth segmentation) using 22 different metrics that were selected as a result of a comprehensive research into the metrics used in the medical volume segmentations."

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
