package:
  name: visceral-evaluatesegmentation
  version: 2021.03.25

source:
  url: https://github.com/Visceral-Project/EvaluateSegmentation/archive/master.zip
  #md5: 321aed8e10e4f7e2f2f1cd2523c69d77
  md5: 3ca792c30a6e5ea566ab4363b818e25e

build:
  number: 1
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage("visceral-evaluatesegmentation", max_pin="x.x") }}

requirements:
  build:
    - libitk-devel
    - libitk 5.3.0
    - make
    - {{ compiler('cxx') }}
    - cmake
  host:
    - libitk-devel
    - libitk 5.3.0
  run:
    - libitk-devel
    - libitk 5.3.0
    - jpeg

test:
  commands:
    - EvaluateSegmentation --help

extra:
  additional-platforms:
    - linux-aarch64

about:
  home: https://github.com/Visceral-Project/EvaluateSegmentation
  license: "Apache License, Version 2.0"
  summary: "EvaluateSegmentation is a tool that compares two volumes (a test segmentation and a ground truth segmentation) using 22 different metrics that were selected as a result of a comprehensive research into the metrics used in the medical volume segmentations."
