{% set name = "Want" %}
{% set version = "0.29" %}

package:
  name: perl-{{ name|lower }}
  version: {{ version }}

source:
  url: http://search.cpan.org/CPAN/authors/id/R/RO/ROBIN/Want-0.29.tar.gz
  md5: 33b2dae5db59781b9a0434fa1db04aab

build:
  number: 7 
  run_exports:
    - {{ pin_subpackage('perl-Want', max_pin='x.x') }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl >=5.26.2
    - perl-module-build >=0.4224

  run:
    - perl >=5.26.2

test:
  imports:
    - Want

about:
  home: http://search.cpan.org/~robin/Want-0.29/Want.pm
  license: perl_5
  summary: "This module generalises the mechanism of the wantarray function, allowing a function."
