{% set version = "1.1.alpha19" %}
{% set sha256 = "ee186044b7fb9fb93cdf44058cd557fd8908d97382217b34753bbe0aef19e6ef" %}


package:
  name: pplacer
  version: '{{ version }}'

source:
  url: https://github.com/18848977154/pplacer/releases/download/v1.1.alpha19/pplacer-1.1.alpha19.zip
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  skip: true   # [osx]
  number: 3

test:
  commands:
    - pplacer --help > /dev/null
    - guppy to_csv --help > /dev/null
    - rppr check --help > /dev/null

about:
  home: http://matsen.fredhutch.org/pplacer/
  license: GPL-3.0
  license_family: GPL
  summary: Pplacer places query sequences on a fixed reference phylogenetic tree to
    maximize phylogenetic likelihood or posterior probability according to a reference
    alignment.
  dev_url: https://github.com/matsen/pplacer/

extra:
  skip-lints:
    - should_be_noarch_generic
