{% set name = "metawrap" %}
{% set version = "1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/bxlab/metaWRAP/archive/refs/tags/v{{ version }}.tar.gz
  md5: 9018a30354fe066b3e936ae625c6f1b7

build:
  noarch: generic
  number: 3
  run_exports:
    - {{ pin_subpackage('metawrap', max_pin="x.x") }}

requirements:
  build:

  run:
    - biopython 1.81.*
    - blast 2.16.0.*
    - bmtagger 3.101.*
    - concoct 1.1.0.*
    - blas 2.127.*
    - bowtie2 2.5.4.*
    - bwa 0.7.18.*
    - checkm-genome 1.2.3.*
    - fastqc 0.11.8.*
    - kraken 1.1.1.*
    - krona 2.7.1.*
    - matplotlib 3.8.4.*
    - maxbin2 2.2.7.*
    - megahit 1.2.9.*
    - metabat2 2.17.*
    - pandas 2.2.2.*
    - pplacer 1.1.alpha19.*
    - r-ggplot2 3.3.3.*
    - r-recommended 4.1.*
    - salmon 1.10.3.*
    - samtools 0.1.19.*
    - seaborn 0.9.0.*
    - spades 4.0.0.*
    - trim-galore 0.6.5.*
    - prokka 1.14.6.*
    - perl-bio-tools-run-alignment-tcoffee 1.7.4.*
    - pasta 1.9.2.*
    - t-coffee
    - quast 5.3.0.*

test:
  commands:
    - which configmetawrap
    - metawrap -h
    - metawrap read_qc -h

about:
  home: https://github.com/bxlab/metaWRAP
  license: MIT
  summary: "MetaWRAP is a pipeline for genome-resolved metagenomic data analysis"
