{% set version = "1.0.1" %}

package:
  name: rust-mdbg
  version: {{ version }}

build:
  number: 5
  noarch: generic
  run_exports:
    - {{ pin_subpackage('rust-mdbg',max_pin="x.x") }}

source:
  url: https://github.com/ekimb/rust-mdbg/archive/v{{ version }}.tar.gz
  sha256: c9c0d2980fff402ee78b5c537140aa2a92aceea74e2f206439c7a42211cbd80b

requirements:
  build:
    - gcc
    - gxx
    - {{ compiler('rust') }}>=1.39
    - pkg-config
  host:
  run:
    

test:
  commands:
    - rust-mdbg --help
    - to_basespace --help

about:
  home: https://github.com/ekimb/rust-mdbg
  license: MIT
  summary: |
    An ultra-fast minimizer-space de Bruijn graph (mdBG) implementation.

extra:
  recipe-maintainers:
    - thanhleviet

