{% set name = "dms" %}
{% set version = "1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/qdu-zyf/dynamic-meta-storms/archive/v{{ version }}.tar.gz
  sha256: c4f90d781465f1fa11d02c33dcd6412a80196889b200aec8493c6cde50e73a4a

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name,max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - llvm-openmp
  host:
    - llvm-openmp
  run:
    - llvm-openmp

test:
  commands:
    - export DynamicMetaStorms=${PREFIX}/bin
    - MS-comp-taxa-dynamic -h 

about:
  home: https://github.com/qibebt-bioinfo/dynamic-meta-storms
  license: GPL3
  license_file: LICENSE  
  summary: "Comprehensive taxonomic and phylogenetic comparison of shotgun metagenomes at the species level"

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btz910
  additional-platforms:
    - linux-aarch64
