{% set name = "hardklor" %}
{% set version = "2.3.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mhoopmann/hardklor/archive/66aea3073913808259af8a26a0f52e839734ae69.tar.gz
  sha256: 2c1cb3e5769376ed21dbe0af776ba86832662162ee36783c0853c5ee7f8ded7b

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - hardklor --help | grep "University of Washington"

about:
  home: "https://github.com/mhoopmann/hardklor"
  license: "Apache-2.0"
  license_family: APACHE
  summary: "Analyze mass spectra."
  dev_url: "https://github.com/mhoopmann/hardklor"
  
extra:
  identifiers:
    - doi:10.1002/0471250953.bi1318s37
  additional-platforms:
    - linux-aarch64
    - osx-arm64
