{% set name = "sak" %}
{% set version = "0.4.11" %}

package:
  name: sak
  version: {{ version }}

source:
  - url: https://github.com/seqan/seqan/archive/refs/tags/seqan-v2.5.0.tar.gz # [linux and aarch64]
    md5: 0db6d52ec51f5ad30f681e8877d549d1 # [linux and aarch64]
  - url:  http://packages.seqan.de/sak/sak-0.4.6-Mac-x86_64.zip  # [osx]
    md5: 09411d5538fb63dfed9568e75bc8c51a  # [osx]
  - url:  http://packages.seqan.de/sak/sak-0.4.6-Linux-x86_64.tar.xz  # [linux]
    md5: cfd68084994e666116971dd681b7fe20  # [linux]

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name|lower) }}

test:
  commands:
    - sak --help 2>&1 > /dev/null

about:
  home: https://github.com/seqan/seqan/tree/master/apps/sak/README
  license: https://github.com/seqan/seqan/tree/master/apps/sak/LICENSE
  summary: This tool allows one to cut sequences and parts of sequences out of sequence files.

extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
