{% set name = "PxBLAT" %}
{% set version = "1.2.1" %}
{% set sha256 = "b61337bde541be6fc933059d42c51364490775071d96de53a60cefeb0ac16e1a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pxblat-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True # [osx]
  #  skip: True  # [not aarch64]
  #  skip: True  # [py < 39]
  script:
    # 设置编译环境变量（关键修复）
    - export CC=aarch64-conda-linux-gnu-cc
    - export CXX=aarch64-conda-linux-gnu-c++
    - export AR=aarch64-conda-linux-gnu-ar
    - export LD=aarch64-conda-linux-gnu-ld
    # 1. 修改common.c文件中的三个错误位置
    - sed -i 's/freeFunc(&el);/freeFunc();/g' src/pxblat/extc/src/core/common.c
    - sed -i 's/free(el);/free();/g' src/pxblat/extc/src/core/common.c
    - sed -i 's/freeFunc(el->val);/freeFunc();/g' src/pxblat/extc/src/core/common.c
    - sed -i 's/if (format != NULL && args != NULL)/if (format != NULL)/g' ./src/pxblat/extc/src/aux/htmshell.c
    - sed -i 's/freeFunc(&hel->val);/freeFunc();/g' src/pxblat/extc/src/core/hash.c
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  entry_points:
    - pxblat = pxblat.cli.cli:app
  run_exports:
    - {{ pin_subpackage('pxblat', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - python <3.12,>=3.9
    - pip
    - setuptools
    - wheel
    - make  # 如果使用Makefile
    - gcc_linux-aarch64  # ARM架构专用编译器
    - gxx_linux-aarch64  # C++编译器
  host:
    - python <3.12,>=3.9
    - pip
    - poetry-core >=1.2.0
    - pybind11 >2.9.1
    - setuptools >=46.4
  run:
    - python <3.12,>=3.9
    - loguru
    - pybind11 >=2.10.4
    - rich
    - pysimdjson >=6.0.2
    - biopython
    - typer
    - deprecated
    - mashumaro
    - urllib3

test:
  imports:
    - pxblat
  commands:
    - pxblat -h

about:
  home: 'https://github.com/ylab-hi/pxblat'
  license: OTHER
  license_file: LICENSE
  summary: "PxBLAT: An Efficient and Ergonomics Python Binding Library for BLAT."
  dev_url: 'https://pypi.org/project/pxblat/'
  doc_url: 'https://pxblat.readthedocs.io/en/latest/'

extra:
  recipe-maintainers:
    - yangyangli
  identifiers:
    - doi:10.1101/2023.08.02.551686
  additional-platforms:
    - linux-aarch64
